#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VENTAS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class db_ventas : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCATEGORIA(CATEGORIA instance);
    partial void UpdateCATEGORIA(CATEGORIA instance);
    partial void DeleteCATEGORIA(CATEGORIA instance);
    partial void InsertDETALLE_PEDIDO(DETALLE_PEDIDO instance);
    partial void UpdateDETALLE_PEDIDO(DETALLE_PEDIDO instance);
    partial void DeleteDETALLE_PEDIDO(DETALLE_PEDIDO instance);
    partial void InsertPEDIDO(PEDIDO instance);
    partial void UpdatePEDIDO(PEDIDO instance);
    partial void DeletePEDIDO(PEDIDO instance);
    partial void InsertPRODUCTO(PRODUCTO instance);
    partial void UpdatePRODUCTO(PRODUCTO instance);
    partial void DeletePRODUCTO(PRODUCTO instance);
    partial void InsertTIPO_USUARIO(TIPO_USUARIO instance);
    partial void UpdateTIPO_USUARIO(TIPO_USUARIO instance);
    partial void DeleteTIPO_USUARIO(TIPO_USUARIO instance);
    partial void InsertUSUARIO(USUARIO instance);
    partial void UpdateUSUARIO(USUARIO instance);
    partial void DeleteUSUARIO(USUARIO instance);
    #endregion
		
		public db_ventas(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_ventas(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_ventas(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_ventas(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CATEGORIA> CATEGORIA
		{
			get
			{
				return this.GetTable<CATEGORIA>();
			}
		}
		
		public System.Data.Linq.Table<Sys_Database_firewall_rules> Sys_Database_firewall_rules
		{
			get
			{
				return this.GetTable<Sys_Database_firewall_rules>();
			}
		}
		
		public System.Data.Linq.Table<DETALLE_PEDIDO> DETALLE_PEDIDO
		{
			get
			{
				return this.GetTable<DETALLE_PEDIDO>();
			}
		}
		
		public System.Data.Linq.Table<PEDIDO> PEDIDO
		{
			get
			{
				return this.GetTable<PEDIDO>();
			}
		}
		
		public System.Data.Linq.Table<PRODUCTO> PRODUCTO
		{
			get
			{
				return this.GetTable<PRODUCTO>();
			}
		}
		
		public System.Data.Linq.Table<TIPO_USUARIO> TIPO_USUARIO
		{
			get
			{
				return this.GetTable<TIPO_USUARIO>();
			}
		}
		
		public System.Data.Linq.Table<USUARIO> USUARIO
		{
			get
			{
				return this.GetTable<USUARIO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CATEGORIA")]
	public partial class CATEGORIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDCATEGORIA;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private string _ESTADO;
		
		private EntitySet<PRODUCTO> _PRODUCTO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCATEGORIAChanging(int value);
    partial void OnIDCATEGORIAChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnDESCRIPCIONChanging(string value);
    partial void OnDESCRIPCIONChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    #endregion
		
		public CATEGORIA()
		{
			this._PRODUCTO = new EntitySet<PRODUCTO>(new Action<PRODUCTO>(this.attach_PRODUCTO), new Action<PRODUCTO>(this.detach_PRODUCTO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCATEGORIA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDCATEGORIA
		{
			get
			{
				return this._IDCATEGORIA;
			}
			set
			{
				if ((this._IDCATEGORIA != value))
				{
					this.OnIDCATEGORIAChanging(value);
					this.SendPropertyChanging();
					this._IDCATEGORIA = value;
					this.SendPropertyChanged("IDCATEGORIA");
					this.OnIDCATEGORIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this.OnDESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION = value;
					this.SendPropertyChanged("DESCRIPCION");
					this.OnDESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__PRODUCTO__IDCATE__38996AB5", Storage="_PRODUCTO", ThisKey="IDCATEGORIA", OtherKey="IDCATEGORIA", DeleteRule="NO ACTION")]
		public EntitySet<PRODUCTO> PRODUCTO
		{
			get
			{
				return this._PRODUCTO;
			}
			set
			{
				this._PRODUCTO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PRODUCTO(PRODUCTO entity)
		{
			this.SendPropertyChanging();
			entity.CATEGORIA = this;
		}
		
		private void detach_PRODUCTO(PRODUCTO entity)
		{
			this.SendPropertyChanging();
			entity.CATEGORIA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.database_firewall_rules")]
	public partial class Sys_Database_firewall_rules
	{
		
		private int _Id;
		
		private string _Name;
		
		private string _Start_ip_address;
		
		private string _End_ip_address;
		
		private System.DateTime _Create_date;
		
		private System.DateTime _Modify_date;
		
		public Sys_Database_firewall_rules()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", DbType="Int NOT NULL IDENTITY")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="name", Storage="_Name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="start_ip_address", Storage="_Start_ip_address", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string Start_ip_address
		{
			get
			{
				return this._Start_ip_address;
			}
			set
			{
				if ((this._Start_ip_address != value))
				{
					this._Start_ip_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="end_ip_address", Storage="_End_ip_address", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string End_ip_address
		{
			get
			{
				return this._End_ip_address;
			}
			set
			{
				if ((this._End_ip_address != value))
				{
					this._End_ip_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="create_date", Storage="_Create_date", DbType="DateTime NOT NULL")]
		public System.DateTime Create_date
		{
			get
			{
				return this._Create_date;
			}
			set
			{
				if ((this._Create_date != value))
				{
					this._Create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="modify_date", Storage="_Modify_date", DbType="DateTime NOT NULL")]
		public System.DateTime Modify_date
		{
			get
			{
				return this._Modify_date;
			}
			set
			{
				if ((this._Modify_date != value))
				{
					this._Modify_date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DETALLE_PEDIDO")]
	public partial class DETALLE_PEDIDO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDPEDIDO;
		
		private int _IDPRODUCTO;
		
		private int _PRECIO;
		
		private int _CANTIDAD;
		
		private EntityRef<PEDIDO> _PEDIDO;
		
		private EntityRef<PRODUCTO> _PRODUCTO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPEDIDOChanging(int value);
    partial void OnIDPEDIDOChanged();
    partial void OnIDPRODUCTOChanging(int value);
    partial void OnIDPRODUCTOChanged();
    partial void OnPRECIOChanging(int value);
    partial void OnPRECIOChanged();
    partial void OnCANTIDADChanging(int value);
    partial void OnCANTIDADChanged();
    #endregion
		
		public DETALLE_PEDIDO()
		{
			this._PEDIDO = default(EntityRef<PEDIDO>);
			this._PRODUCTO = default(EntityRef<PRODUCTO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPEDIDO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDPEDIDO
		{
			get
			{
				return this._IDPEDIDO;
			}
			set
			{
				if ((this._IDPEDIDO != value))
				{
					if (this._PEDIDO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDPEDIDOChanging(value);
					this.SendPropertyChanging();
					this._IDPEDIDO = value;
					this.SendPropertyChanged("IDPEDIDO");
					this.OnIDPEDIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPRODUCTO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDPRODUCTO
		{
			get
			{
				return this._IDPRODUCTO;
			}
			set
			{
				if ((this._IDPRODUCTO != value))
				{
					if (this._PRODUCTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDPRODUCTOChanging(value);
					this.SendPropertyChanging();
					this._IDPRODUCTO = value;
					this.SendPropertyChanged("IDPRODUCTO");
					this.OnIDPRODUCTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Int NOT NULL")]
		public int PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this.OnPRECIOChanging(value);
					this.SendPropertyChanging();
					this._PRECIO = value;
					this.SendPropertyChanged("PRECIO");
					this.OnPRECIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDAD", DbType="Int NOT NULL")]
		public int CANTIDAD
		{
			get
			{
				return this._CANTIDAD;
			}
			set
			{
				if ((this._CANTIDAD != value))
				{
					this.OnCANTIDADChanging(value);
					this.SendPropertyChanging();
					this._CANTIDAD = value;
					this.SendPropertyChanged("CANTIDAD");
					this.OnCANTIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__DETALLE_P__IDPED__440B1D61", Storage="_PEDIDO", ThisKey="IDPEDIDO", OtherKey="IDPEDIDO", IsForeignKey=true)]
		public PEDIDO PEDIDO
		{
			get
			{
				return this._PEDIDO.Entity;
			}
			set
			{
				PEDIDO previousValue = this._PEDIDO.Entity;
				if (((previousValue != value) 
							|| (this._PEDIDO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PEDIDO.Entity = null;
						previousValue.DETALLE_PEDIDO.Remove(this);
					}
					this._PEDIDO.Entity = value;
					if ((value != null))
					{
						value.DETALLE_PEDIDO.Add(this);
						this._IDPEDIDO = value.IDPEDIDO;
					}
					else
					{
						this._IDPEDIDO = default(int);
					}
					this.SendPropertyChanged("PEDIDO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__DETALLE_P__IDPRO__4316F928", Storage="_PRODUCTO", ThisKey="IDPRODUCTO", OtherKey="IDPRODUCTO", IsForeignKey=true)]
		public PRODUCTO PRODUCTO
		{
			get
			{
				return this._PRODUCTO.Entity;
			}
			set
			{
				PRODUCTO previousValue = this._PRODUCTO.Entity;
				if (((previousValue != value) 
							|| (this._PRODUCTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PRODUCTO.Entity = null;
						previousValue.DETALLE_PEDIDO.Remove(this);
					}
					this._PRODUCTO.Entity = value;
					if ((value != null))
					{
						value.DETALLE_PEDIDO.Add(this);
						this._IDPRODUCTO = value.IDPRODUCTO;
					}
					else
					{
						this._IDPRODUCTO = default(int);
					}
					this.SendPropertyChanged("PRODUCTO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PEDIDO")]
	public partial class PEDIDO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDPEDIDO;
		
		private System.DateTime _FECHA;
		
		private string _ESTADO;
		
		private int _IDUSUARIO;
		
		private EntitySet<DETALLE_PEDIDO> _DETALLE_PEDIDO;
		
		private EntityRef<USUARIO> _USUARIO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPEDIDOChanging(int value);
    partial void OnIDPEDIDOChanged();
    partial void OnFECHAChanging(System.DateTime value);
    partial void OnFECHAChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    partial void OnIDUSUARIOChanging(int value);
    partial void OnIDUSUARIOChanged();
    #endregion
		
		public PEDIDO()
		{
			this._DETALLE_PEDIDO = new EntitySet<DETALLE_PEDIDO>(new Action<DETALLE_PEDIDO>(this.attach_DETALLE_PEDIDO), new Action<DETALLE_PEDIDO>(this.detach_DETALLE_PEDIDO));
			this._USUARIO = default(EntityRef<USUARIO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPEDIDO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDPEDIDO
		{
			get
			{
				return this._IDPEDIDO;
			}
			set
			{
				if ((this._IDPEDIDO != value))
				{
					this.OnIDPEDIDOChanging(value);
					this.SendPropertyChanging();
					this._IDPEDIDO = value;
					this.SendPropertyChanged("IDPEDIDO");
					this.OnIDPEDIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA
		{
			get
			{
				return this._FECHA;
			}
			set
			{
				if ((this._FECHA != value))
				{
					this.OnFECHAChanging(value);
					this.SendPropertyChanging();
					this._FECHA = value;
					this.SendPropertyChanged("FECHA");
					this.OnFECHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUSUARIO", DbType="Int NOT NULL")]
		public int IDUSUARIO
		{
			get
			{
				return this._IDUSUARIO;
			}
			set
			{
				if ((this._IDUSUARIO != value))
				{
					if (this._USUARIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDUSUARIOChanging(value);
					this.SendPropertyChanging();
					this._IDUSUARIO = value;
					this.SendPropertyChanged("IDUSUARIO");
					this.OnIDUSUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__DETALLE_P__IDPED__440B1D61", Storage="_DETALLE_PEDIDO", ThisKey="IDPEDIDO", OtherKey="IDPEDIDO", DeleteRule="NO ACTION")]
		public EntitySet<DETALLE_PEDIDO> DETALLE_PEDIDO
		{
			get
			{
				return this._DETALLE_PEDIDO;
			}
			set
			{
				this._DETALLE_PEDIDO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__PEDIDO__IDUSUARI__403A8C7D", Storage="_USUARIO", ThisKey="IDUSUARIO", OtherKey="IDUSUARIO", IsForeignKey=true)]
		public USUARIO USUARIO
		{
			get
			{
				return this._USUARIO.Entity;
			}
			set
			{
				USUARIO previousValue = this._USUARIO.Entity;
				if (((previousValue != value) 
							|| (this._USUARIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USUARIO.Entity = null;
						previousValue.PEDIDO.Remove(this);
					}
					this._USUARIO.Entity = value;
					if ((value != null))
					{
						value.PEDIDO.Add(this);
						this._IDUSUARIO = value.IDUSUARIO;
					}
					else
					{
						this._IDUSUARIO = default(int);
					}
					this.SendPropertyChanged("USUARIO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DETALLE_PEDIDO(DETALLE_PEDIDO entity)
		{
			this.SendPropertyChanging();
			entity.PEDIDO = this;
		}
		
		private void detach_DETALLE_PEDIDO(DETALLE_PEDIDO entity)
		{
			this.SendPropertyChanging();
			entity.PEDIDO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCTO")]
	public partial class PRODUCTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDPRODUCTO;
		
		private int _IDCATEGORIA;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private int _PRECIO;
		
		private int _STOCK;
		
		private string _PORTADA;
		
		private int _IMPORTANCIA;
		
		private string _IMAGEN;
		
		private string _ESTADO;
		
		private EntitySet<DETALLE_PEDIDO> _DETALLE_PEDIDO;
		
		private EntityRef<CATEGORIA> _CATEGORIA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPRODUCTOChanging(int value);
    partial void OnIDPRODUCTOChanged();
    partial void OnIDCATEGORIAChanging(int value);
    partial void OnIDCATEGORIAChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnDESCRIPCIONChanging(string value);
    partial void OnDESCRIPCIONChanged();
    partial void OnPRECIOChanging(int value);
    partial void OnPRECIOChanged();
    partial void OnSTOCKChanging(int value);
    partial void OnSTOCKChanged();
    partial void OnPORTADAChanging(string value);
    partial void OnPORTADAChanged();
    partial void OnIMPORTANCIAChanging(int value);
    partial void OnIMPORTANCIAChanged();
    partial void OnIMAGENChanging(string value);
    partial void OnIMAGENChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    #endregion
		
		public PRODUCTO()
		{
			this._DETALLE_PEDIDO = new EntitySet<DETALLE_PEDIDO>(new Action<DETALLE_PEDIDO>(this.attach_DETALLE_PEDIDO), new Action<DETALLE_PEDIDO>(this.detach_DETALLE_PEDIDO));
			this._CATEGORIA = default(EntityRef<CATEGORIA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPRODUCTO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDPRODUCTO
		{
			get
			{
				return this._IDPRODUCTO;
			}
			set
			{
				if ((this._IDPRODUCTO != value))
				{
					this.OnIDPRODUCTOChanging(value);
					this.SendPropertyChanging();
					this._IDPRODUCTO = value;
					this.SendPropertyChanged("IDPRODUCTO");
					this.OnIDPRODUCTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCATEGORIA", DbType="Int NOT NULL")]
		public int IDCATEGORIA
		{
			get
			{
				return this._IDCATEGORIA;
			}
			set
			{
				if ((this._IDCATEGORIA != value))
				{
					if (this._CATEGORIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDCATEGORIAChanging(value);
					this.SendPropertyChanging();
					this._IDCATEGORIA = value;
					this.SendPropertyChanged("IDCATEGORIA");
					this.OnIDCATEGORIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(50)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this.OnDESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION = value;
					this.SendPropertyChanged("DESCRIPCION");
					this.OnDESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Int NOT NULL")]
		public int PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this.OnPRECIOChanging(value);
					this.SendPropertyChanging();
					this._PRECIO = value;
					this.SendPropertyChanged("PRECIO");
					this.OnPRECIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCK", DbType="Int NOT NULL")]
		public int STOCK
		{
			get
			{
				return this._STOCK;
			}
			set
			{
				if ((this._STOCK != value))
				{
					this.OnSTOCKChanging(value);
					this.SendPropertyChanging();
					this._STOCK = value;
					this.SendPropertyChanged("STOCK");
					this.OnSTOCKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PORTADA", DbType="Char(1) NOT NULL", CanBeNull=false)]
		public string PORTADA
		{
			get
			{
				return this._PORTADA;
			}
			set
			{
				if ((this._PORTADA != value))
				{
					this.OnPORTADAChanging(value);
					this.SendPropertyChanging();
					this._PORTADA = value;
					this.SendPropertyChanged("PORTADA");
					this.OnPORTADAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMPORTANCIA", DbType="Int NOT NULL")]
		public int IMPORTANCIA
		{
			get
			{
				return this._IMPORTANCIA;
			}
			set
			{
				if ((this._IMPORTANCIA != value))
				{
					this.OnIMPORTANCIAChanging(value);
					this.SendPropertyChanging();
					this._IMPORTANCIA = value;
					this.SendPropertyChanged("IMPORTANCIA");
					this.OnIMPORTANCIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGEN", DbType="VarChar(50)")]
		public string IMAGEN
		{
			get
			{
				return this._IMAGEN;
			}
			set
			{
				if ((this._IMAGEN != value))
				{
					this.OnIMAGENChanging(value);
					this.SendPropertyChanging();
					this._IMAGEN = value;
					this.SendPropertyChanged("IMAGEN");
					this.OnIMAGENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(1)")]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__DETALLE_P__IDPRO__4316F928", Storage="_DETALLE_PEDIDO", ThisKey="IDPRODUCTO", OtherKey="IDPRODUCTO", DeleteRule="NO ACTION")]
		public EntitySet<DETALLE_PEDIDO> DETALLE_PEDIDO
		{
			get
			{
				return this._DETALLE_PEDIDO;
			}
			set
			{
				this._DETALLE_PEDIDO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__PRODUCTO__IDCATE__38996AB5", Storage="_CATEGORIA", ThisKey="IDCATEGORIA", OtherKey="IDCATEGORIA", IsForeignKey=true)]
		public CATEGORIA CATEGORIA
		{
			get
			{
				return this._CATEGORIA.Entity;
			}
			set
			{
				CATEGORIA previousValue = this._CATEGORIA.Entity;
				if (((previousValue != value) 
							|| (this._CATEGORIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CATEGORIA.Entity = null;
						previousValue.PRODUCTO.Remove(this);
					}
					this._CATEGORIA.Entity = value;
					if ((value != null))
					{
						value.PRODUCTO.Add(this);
						this._IDCATEGORIA = value.IDCATEGORIA;
					}
					else
					{
						this._IDCATEGORIA = default(int);
					}
					this.SendPropertyChanged("CATEGORIA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DETALLE_PEDIDO(DETALLE_PEDIDO entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCTO = this;
		}
		
		private void detach_DETALLE_PEDIDO(DETALLE_PEDIDO entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCTO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TIPO_USUARIO")]
	public partial class TIPO_USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDTIPOUSUARIO;
		
		private string _NOMBRE;
		
		private string _ESTADO;
		
		private EntitySet<USUARIO> _USUARIO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTIPOUSUARIOChanging(int value);
    partial void OnIDTIPOUSUARIOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    #endregion
		
		public TIPO_USUARIO()
		{
			this._USUARIO = new EntitySet<USUARIO>(new Action<USUARIO>(this.attach_USUARIO), new Action<USUARIO>(this.detach_USUARIO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTIPOUSUARIO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDTIPOUSUARIO
		{
			get
			{
				return this._IDTIPOUSUARIO;
			}
			set
			{
				if ((this._IDTIPOUSUARIO != value))
				{
					this.OnIDTIPOUSUARIOChanging(value);
					this.SendPropertyChanging();
					this._IDTIPOUSUARIO = value;
					this.SendPropertyChanged("IDTIPOUSUARIO");
					this.OnIDTIPOUSUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__USUARIO__IDTIPOU__3D5E1FD2", Storage="_USUARIO", ThisKey="IDTIPOUSUARIO", OtherKey="IDTIPOUSUARIO", DeleteRule="NO ACTION")]
		public EntitySet<USUARIO> USUARIO
		{
			get
			{
				return this._USUARIO;
			}
			set
			{
				this._USUARIO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_USUARIO(USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TIPO_USUARIO = this;
		}
		
		private void detach_USUARIO(USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TIPO_USUARIO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USUARIO")]
	public partial class USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDUSUARIO;
		
		private int _IDTIPOUSUARIO;
		
		private string _NOMBREUSU;
		
		private string _PASSWORD;
		
		private string _NOMBRE;
		
		private string _APELLIDOS;
		
		private string _EMAIL;
		
		private string _FOTO;
		
		private string _ESTADO;
		
		private EntitySet<PEDIDO> _PEDIDO;
		
		private EntityRef<TIPO_USUARIO> _TIPO_USUARIO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUSUARIOChanging(int value);
    partial void OnIDUSUARIOChanged();
    partial void OnIDTIPOUSUARIOChanging(int value);
    partial void OnIDTIPOUSUARIOChanged();
    partial void OnNOMBREUSUChanging(string value);
    partial void OnNOMBREUSUChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnAPELLIDOSChanging(string value);
    partial void OnAPELLIDOSChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnFOTOChanging(string value);
    partial void OnFOTOChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    #endregion
		
		public USUARIO()
		{
			this._PEDIDO = new EntitySet<PEDIDO>(new Action<PEDIDO>(this.attach_PEDIDO), new Action<PEDIDO>(this.detach_PEDIDO));
			this._TIPO_USUARIO = default(EntityRef<TIPO_USUARIO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUSUARIO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDUSUARIO
		{
			get
			{
				return this._IDUSUARIO;
			}
			set
			{
				if ((this._IDUSUARIO != value))
				{
					this.OnIDUSUARIOChanging(value);
					this.SendPropertyChanging();
					this._IDUSUARIO = value;
					this.SendPropertyChanged("IDUSUARIO");
					this.OnIDUSUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTIPOUSUARIO", DbType="Int NOT NULL")]
		public int IDTIPOUSUARIO
		{
			get
			{
				return this._IDTIPOUSUARIO;
			}
			set
			{
				if ((this._IDTIPOUSUARIO != value))
				{
					if (this._TIPO_USUARIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTIPOUSUARIOChanging(value);
					this.SendPropertyChanging();
					this._IDTIPOUSUARIO = value;
					this.SendPropertyChanged("IDTIPOUSUARIO");
					this.OnIDTIPOUSUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBREUSU", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOMBREUSU
		{
			get
			{
				return this._NOMBREUSU;
			}
			set
			{
				if ((this._NOMBREUSU != value))
				{
					this.OnNOMBREUSUChanging(value);
					this.SendPropertyChanging();
					this._NOMBREUSU = value;
					this.SendPropertyChanged("NOMBREUSU");
					this.OnNOMBREUSUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this.OnAPELLIDOSChanging(value);
					this.SendPropertyChanging();
					this._APELLIDOS = value;
					this.SendPropertyChanged("APELLIDOS");
					this.OnAPELLIDOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOTO", DbType="VarChar(250)")]
		public string FOTO
		{
			get
			{
				return this._FOTO;
			}
			set
			{
				if ((this._FOTO != value))
				{
					this.OnFOTOChanging(value);
					this.SendPropertyChanging();
					this._FOTO = value;
					this.SendPropertyChanged("FOTO");
					this.OnFOTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__PEDIDO__IDUSUARI__403A8C7D", Storage="_PEDIDO", ThisKey="IDUSUARIO", OtherKey="IDUSUARIO", DeleteRule="NO ACTION")]
		public EntitySet<PEDIDO> PEDIDO
		{
			get
			{
				return this._PEDIDO;
			}
			set
			{
				this._PEDIDO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__USUARIO__IDTIPOU__3D5E1FD2", Storage="_TIPO_USUARIO", ThisKey="IDTIPOUSUARIO", OtherKey="IDTIPOUSUARIO", IsForeignKey=true)]
		public TIPO_USUARIO TIPO_USUARIO
		{
			get
			{
				return this._TIPO_USUARIO.Entity;
			}
			set
			{
				TIPO_USUARIO previousValue = this._TIPO_USUARIO.Entity;
				if (((previousValue != value) 
							|| (this._TIPO_USUARIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TIPO_USUARIO.Entity = null;
						previousValue.USUARIO.Remove(this);
					}
					this._TIPO_USUARIO.Entity = value;
					if ((value != null))
					{
						value.USUARIO.Add(this);
						this._IDTIPOUSUARIO = value.IDTIPOUSUARIO;
					}
					else
					{
						this._IDTIPOUSUARIO = default(int);
					}
					this.SendPropertyChanged("TIPO_USUARIO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PEDIDO(PEDIDO entity)
		{
			this.SendPropertyChanging();
			entity.USUARIO = this;
		}
		
		private void detach_PEDIDO(PEDIDO entity)
		{
			this.SendPropertyChanging();
			entity.USUARIO = null;
		}
	}
}
#pragma warning restore 1591
